# Generated by Django 5.2.6 on 2025-09-22 03:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BaseItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_id', models.CharField(max_length=100, unique=True, verbose_name='Item ID')),
                ('category', models.CharField(choices=[('Pump', 'Pump'), ('Filter', 'Filter'), ('Mix Tank', 'Mix Tank'), ('Valve', 'Valve'), ('Command Center', 'Command Center'), ('Misc', 'Misc')], max_length=50)),
                ('description', models.TextField(blank=True)),
                ('vendor', models.CharField(blank=True, max_length=100)),
                ('rating', models.CharField(blank=True, max_length=50)),
                ('location', models.CharField(blank=True, max_length=100)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['item_id'],
            },
        ),
        migrations.CreateModel(
            name='CommandCenter',
            fields=[
                ('baseitem_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='inventory.baseitem')),
            ],
            bases=('inventory.baseitem',),
        ),
        migrations.CreateModel(
            name='Filter',
            fields=[
                ('baseitem_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='inventory.baseitem')),
                ('inlet', models.CharField(blank=True, max_length=50)),
                ('outlet', models.CharField(blank=True, max_length=50)),
                ('moc', models.CharField(blank=True, max_length=100, verbose_name='Material of Construction')),
                ('filter_type', models.CharField(blank=True, max_length=100, verbose_name='Filter Type')),
            ],
            bases=('inventory.baseitem',),
        ),
        migrations.CreateModel(
            name='Misc',
            fields=[
                ('baseitem_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='inventory.baseitem')),
                ('speed', models.CharField(blank=True, max_length=50)),
                ('inlet', models.CharField(blank=True, max_length=50)),
                ('outlet', models.CharField(blank=True, max_length=50)),
                ('moc', models.CharField(blank=True, max_length=100, verbose_name='Material of Construction')),
                ('power', models.CharField(blank=True, max_length=50)),
                ('quantity', models.CharField(blank=True, max_length=50)),
            ],
            bases=('inventory.baseitem',),
        ),
        migrations.CreateModel(
            name='MixTank',
            fields=[
                ('baseitem_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='inventory.baseitem')),
                ('inlet', models.CharField(blank=True, max_length=50)),
                ('outlet', models.CharField(blank=True, max_length=50)),
                ('moc', models.CharField(blank=True, max_length=100, verbose_name='Material of Construction')),
                ('power', models.CharField(blank=True, max_length=50)),
            ],
            bases=('inventory.baseitem',),
        ),
        migrations.CreateModel(
            name='Pump',
            fields=[
                ('baseitem_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='inventory.baseitem')),
                ('speed', models.CharField(blank=True, max_length=50)),
                ('inlet', models.CharField(blank=True, max_length=50)),
                ('outlet', models.CharField(blank=True, max_length=50)),
                ('moc', models.CharField(blank=True, max_length=100, verbose_name='Material of Construction')),
                ('power', models.CharField(blank=True, max_length=50)),
            ],
            bases=('inventory.baseitem',),
        ),
        migrations.CreateModel(
            name='Valve',
            fields=[
                ('baseitem_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='inventory.baseitem')),
                ('moc', models.CharField(blank=True, max_length=100, verbose_name='Material of Construction')),
                ('size', models.CharField(blank=True, max_length=50)),
                ('valve_type', models.CharField(blank=True, max_length=100, verbose_name='Valve Type')),
            ],
            bases=('inventory.baseitem',),
        ),
    ]
